### ISSUE TITLE
installation guide for osx?

### ISSUE THREAD

**Issue by seansay** [MTG/sms-tools#14]
I created a virtualenv, and install all the dependecies and it works

**Comment by flothesof** [comment]
@seansay : could you give a little more details on how you did it on OSX? I'm stuck after cloning the repo, because the compilation of the C functions stops with the following error message:

'''
gcc -bundle -undefined dynamic_lookup -L/Users/kappamaki/anaconda/envs/py27-opencv/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.5-x86_64-2.7/utilFunctions.o build/temp.macosx-10.5-x86_64-2.7/cutilFunctions.o -L/Users/kappamaki/anaconda/envs/py27-opencv/lib -lm -o /Users/kappamaki/workspace/coursera-aspma/sms-tools/software/models/utilFunctions_C/utilFunctions_C.so
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'gcc' failed with exit status 1
'''

**Comment by alemangui** [comment]
Hello,

I agree with @Lykathia, virtualenv is the way to go. 

Here's what I did on Mac OS:

- Install virtualenv:
```sudo pip install virtualenv```

- Go to the folder where you have sms-tools and create an environment by typing:
```virtualenv venv```

- To activate the environment (which you'll have to do when you work on sms-tools) do:
```. venv/bin/activate```

- With the environment active install all the stuff you need
```pip install ipython numpy matplotlib scipy cython```

- And normally you should have no errors (only several warnings) when compiling the C functions
```cd software/models/utilFunctions_C```
```python compileModule.py build_ext --inplace```

**Comment by flothesof** [comment]
Hey!

Thanks for your reply.
Actually, even though I'm not doing a virtualenv, I'm doing something
similar: using conda to create a python 2.7 installation from which I tried
to compile the cython functions.

The part I don't get is where the errors come from. What libraries is the
compiler missing? It's just not clear to me.

Thanks for posting your code. I'll try to make it work like this.

Regards

Florian

**Comment by flothesof** [comment]
I finally managed to do it using Anaconda. It's very similar to the virtualenv way of doing it.

I wrote the procedure up here:

http://flothesof.github.io/sms-tools-MacOSX-Anaconda.html

Best,

Florian

**Comment by bzamecnik** [comment]
Nice guide, Forian!

I'm happy to announce a quite simple installation process thanks to packaging sms-tools so that it can be installed via pip.

https://class.coursera.org/audio-002/forum/thread?thread_id=865#comment-1630

**Comment by greekgoddj** [comment]
Nice work Florian!

**Comment by xserra** [comment]
closing this one.
