### ISSUE TITLE
Plotting the spectrum in STFT/Stochastic/SPS/HPS model does not work.

### ISSUE THREAD

**Issue by fllprbt** [MTG/sms-tools#55]
#Same problem everywhere, `TypeError: 'float' object cannot be interpreted as an index`

**STFT** is solved :: #52

**Comment by GarrettArm** [comment]
rolling back to numpy version 1.11.0 solves this issue.  `pip install numpy==1.11.0`

i do not understand the sms-tools code well enough to revise it, but rolling back numpy is a solution.

**Comment by aamirmalik** [comment]
I rolled back numpy to 1.11.0 as suggested. It seems that there are some incompatibility with numpy 1.12.1. After rolling back i get deprication warnings : "stft_function.py:70: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future"



Aamirs-MBP:models_interface amalik$ pip2.7 install numpy==1.11.0
Collecting numpy==1.11.0
  Downloading numpy-1.11.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.9MB)
    100% |████████████████████████████████| 3.9MB 293kB/s 
Installing collected packages: numpy
  Found existing installation: numpy 1.12.1
    Uninstalling numpy-1.12.1:
      Successfully uninstalled numpy-1.12.1
Successfully installed numpy-1.11.0


Aamirs-MBP:models_interface amalik$ python models_GUI.py 
/Users/amalik/Google Drive/Courses/AudioSignalProcessingForMusicApplications/sms-tools/software/models_interface/stft_function.py:59: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  plt.pcolormesh(frmTime, binFreq, np.transpose(mX[:,:N*maxplotfreq/fs+1]))
/Users/amalik/Google Drive/Courses/AudioSignalProcessingForMusicApplications/sms-tools/software/models_interface/stft_function.py:70: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  plt.pcolormesh(frmTime, binFreq, np.transpose(np.diff(pX[:,:N*maxplotfreq/fs+1],axis=1)))

**Comment by DavidAntliff** [comment]
@aamirmalik it's a known issue as it uses floats for array indices. It has been reported on the course forum, has a simple fix (wrap with `int()`), and doesn't cause any numerical problems.
