### ISSUE TITLE
Suggestion:  use conda manage packages and environment

### ISSUE THREAD

**Issue by Garlandal** [MTG/sms-tools#58]
I got some errors where i use this tool and mostly due to the environment or some package version, such as https://github.com/MTG/sms-tools/issues/49 

 So i wander if this project can use [conda](https://conda.io/docs/) which is a good package management system and environment management system to manage these kind of scientific packages.

This would be a friendly feature to our beginners who are troubling with debugging on how-to-get-it -work questions

**Comment by EMCP** [comment]
pip is the defactor package manager for python 2 and 3 ..

**Comment by vichug** [comment]
Hey, of course you can create a python env using conda to use sms-tools. The process is as straightforward as for any other conda env : 
``conda create -n sms-tools-env ipython numpy matplotlib scipy cython``
In one command line it will create the environment, and install the packages needed for the courses. However, as far as i know, those install will not be through ``pip`` but through the conda ``conda install`` command ; so they will be local to this conda env and theoretically lead to less potential version conflict.
Then to use this environment, just activate it :
``source activate sms-tools-env``
you should be ready to go.
(If you already have an environment that you wish to work in, just ``source activate`` then install the dependencies : 
``conda install ipython numpy matplotlib scipy cython``  )
However, this should not be a suggestion/feature request, because it is only depending on the needs and will of the user and it's kinda beyond the scope of this course
